### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by liampauling** [liampauling/flumine#248]
Flumine seems to leak memory when left running for extended periods, I believe it is due to order data not being collected by the GC but I am not sure why. 

Image shows instance_016 leaking, the other instances are just data stream instances (no orders or market data)

![leaky](https://user-images.githubusercontent.com/12016537/89163536-a3886d00-d56d-11ea-8270-3bb454947c63.png)

**Comment by liampauling** [comment]
Data recorder now leaks, likely due to `Market` objects being created and/or the `MarketCatalogue` worker

![leak_05092020](https://user-images.githubusercontent.com/12016537/92299358-87e7fc00-ef49-11ea-94bc-5b59f8ce5ed2.png)

**Comment by synapticarbors** [comment]
I haven't tested this at all, but could it be due to the circular reference between the blotter and the market?

https://github.com/liampauling/flumine/blob/274c002debbaf875e0d954fc366ba8d7b3e2a512/flumine/markets/market.py#L28

You might test using the `weakref` module to break the circular reference:
https://docs.python.org/3/library/weakref.html

**Comment by liampauling** [comment]
Good point, I will look to do some testing on this early next week 👍

**Comment by liampauling** [comment]
I have tried two changes and no difference made on memory

- https://github.com/liampauling/flumine/commit/71aa2618165dc4ab540c962d3a77774572ab873c
- https://github.com/liampauling/flumine/commit/75afa64708136ee69991ce968a7be58d950e1e93

Not sure if the circular reference is completely fixed, however going back to the drawing board to try and isolate what is causing this.

**Comment by synapticarbors** [comment]
Ok, disappointed that it wasn't a simple fix. Also for reference, it's sometimes easier to use `weakref.proxy` rather than `weakref.ref`, so you don't have to change things to call `foo.a()` instead of just `foo.a`. 

Also when I've hunted for memory leaks in python, I found it useful to set `gc.set_debug(gc.DEBUG_SAVEALL)` and then look at what is in `gc.garbage`. You'll have to filter it, but something might stand out. I've also played around with https://docs.python.org/3/library/tracemalloc.html, but had less luck with it.

**Comment by liampauling** [comment]
Ah that would help 👍

Yeah I have no idea how to get anything good from tracing, I will have a look at interrogating the gc.

**Comment by liampauling** [comment]
The memory leak is in bflw and not flumine (although RunnerContext needs to be cleaned up), I have underestimated the amount of memory the cache can take up when streaming large numbers of markets / orders.

![Screenshot 2020-10-07 at 08 08 15](https://user-images.githubusercontent.com/12016537/95298703-6b0a5580-0874-11eb-8718-af5cf7768448.png)

Used pympler and muppy to track number of objects and size.
